# Generated by Django 3.1.7 on 2021-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Text')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default=('new', 'Новая'), max_length=200, verbose_name='Status')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Change time')),
            ],
        ),
    ]
