# Generated by Django 3.1.7 on 2021-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210226_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='about_list',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
